Homework 5
sofi388/Vereshchagina-Sofia-HW pull request #6
Opened 2022-04-29 20:22 UTC by sofi388

Homework 5
Не успеваю пофиксить к 30.04. проблему с драйвером. Практически доделала, но когда начала менять структуру программы - сломалась она в месте вызова конструктора базового класса MainStep. 
Отсюда вопрос, я понимаю, что скорее всего такой дедлайн был назначен т.к. вы заканчиваете 4 курс раньше. Однако получается, что поскольку я не успеваю разобраться с этой проблемой, у меня безнадежно допса? Или может быть, будет человек, который сможет проверить (в случае если все же мне удастся исправить ошибку) в мае?
С уважением,
Софья

2022-05-04 15:14 UTC, obitkin requested changes

2022-05-04 15:14 UTC, obitkin commented on src/test/java/hw5/steps/CucumberHook.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
А зачем это вам тут? Уже же есть в BeforeSuit

2022-05-04 15:14 UTC, obitkin commented on src/test/java/hw5/Table.java
> +    WebElement log;
Нечитаемо

2022-05-04 15:14 UTC, obitkin commented on src/test/java/hw5/steps/AssertStep.java
> +    }
Нечитаемое, разбейте стрим на несколько строк, каждая новая строка - операция над стримом

2022-05-05 18:57 UTC, sofi388 commented
Можете пожалуйста прикрепить документы с описанием 3-5 лабораторных работ? Мне нужно для отчета. Скайп  я ваш не записала, а teams не работает, соответственно я не могу ни посмотреть описание заданий, ни вам написать.

2022-05-09 11:18 UTC, obitkin approved these changes
Пятая работа принята

2022-05-09 11:20 UTC, merged